### ISSUE TITLE
Queue::setConfig issues

### ISSUE THREAD

**Issue by NeroAdvents** [scherersoftware/cake-websocket#15]
Hi,

I started using your plugin today and I encountered some issues while installing and configuring it on my CakePHP project (v3.8.13).
```
Exception: The "default" queue configuration does not exist. in [/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php, line 221]
2020-08-06 14:08:23 Error: [InvalidArgumentException] The "default" queue configuration does not exist. in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php on line 221
Stack Trace:
#0 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/josegonzalez/cakephp-queuesadilla/src/Queue/Queue.php(251): Josegonzalez\CakeQueuesadilla\Queue\Queue::_buildEngine()
#1 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/scherersoftware/cake-websocket/src/Shell/WebsocketServerShell.php(58): Josegonzalez\CakeQueuesadilla\Queue\Queue::engine()
#2 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Console/Shell.php(531): Websocket\Shell\WebsocketServerShell->main()
#3 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Console/CommandRunner.php(385): Cake\Console\Shell->runCommand()
#4 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell()
#5 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/bin/cake.php(12): Cake\Console\CommandRunner->run()
#6 {main}
```
I managed to resolve this one by adding this lines of code to my bootstrap.php file:
```
Queue::setConfig('default', [
    'engine' => 'josegonzalez\Queuesadilla\Engine\MysqlEngine',
    'database'=>'cakephp',
    'host'=>'localhost',
    'user'=>'root',
    'pass'=>'password',
]);
```
But since when I run my app using **bin/cake websocket_server** command line, nothing happens. It's like the app is looping and I don't know how to resolve this problem. What did I do wrong ? Am I missing something ? Is there any good tutorial ?
Thx.

**EDIT**

Now after looping for a while, I got these errors messages:
```
PHP Warning:  include(/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/Debugger.php): failed to open stream: Too many open files in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444

Warning: include(/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/Debugger.php): failed to open stream: Too many open files in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/../cakephp/cakephp/src/Error/Debugger.php' for inclusion (include_path='.:/usr/share/php') in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/../cakephp/cakephp/src/Error/Debugger.php' for inclusion (include_path='.:/usr/share/php') in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/Debugger.php): failed to open stream: Too many open files in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444

Warning: include(/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/Debugger.php): failed to open stream: Too many open files in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/../cakephp/cakephp/src/Error/Debugger.php' for inclusion (include_path='.:/usr/share/php') in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/../cakephp/cakephp/src/Error/Debugger.php' for inclusion (include_path='.:/usr/share/php') in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'Cake\Error\Debugger' not found in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php:164
Stack trace:
#0 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php(444): Cake\Error\BaseErrorHandler->handleError()
#1 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php(444): include()
#2 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(184): spl_autoload_call()
#5 [internal function]: Cake\Error\BaseErrorHandler->wrapAndHandleException()
#6 {main}
  thrown in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php on line 164

Fatal error: Uncaught Error: Class 'Cake\Error\Debugger' not found in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php:164
Stack trace:
#0 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php(444): Cake\Error\BaseErrorHandler->handleError()
#1 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php(444): include()
#2 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(184): spl_autoload_call()
#5 [internal function]: Cake\Error\BaseErrorHandler->wrapAndHandleException()
#6 {main}
  thrown in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php on line 164
PHP Warning:  include(/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/Debugger.php): failed to open stream: Too many open files in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444

Warning: include(/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/Debugger.php): failed to open stream: Too many open files in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/../cakephp/cakephp/src/Error/Debugger.php' for inclusion (include_path='.:/usr/share/php') in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/../cakephp/cakephp/src/Error/Debugger.php' for inclusion (include_path='.:/usr/share/php') in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'Cake\Error\Debugger' not found in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php:164
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleError()
#1 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php(133): file_put_contents()
#2 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/psr/log/Psr/Log/AbstractLogger.php(113): Cake\Log\Engine\FileLog->log()
#3 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/josegonzalez/queuesadilla/src/josegonzalez/Queuesadilla/Worker/Base.php(69): Psr\Log\AbstractLogger->info()
#4 [internal function]: josegonzalez\Queuesadilla\Worker\Base->shutdownHandler()
#5 {main}
  thrown in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php on line 164

Fatal error: Uncaught Error: Class 'Cake\Error\Debugger' not found in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php:164
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleError()
#1 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php(133): file_put_contents()
#2 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/psr/log/Psr/Log/AbstractLogger.php(113): Cake\Log\Engine\FileLog->log()
#3 /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/josegonzalez/queuesadilla/src/josegonzalez/Queuesadilla/Worker/Base.php(69): Psr\Log\AbstractLogger->info()
#4 [internal function]: josegonzalez\Queuesadilla\Worker\Base->shutdownHandler()
#5 {main}
  thrown in /home/nordine/PhpstormProjects/Websockets/cakephp/cms/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php on line 164
```

**Comment by felixkempf** [comment]
Hi NeroAdvents,

the `bin/cake websocket_server` looping forever and having no output is indeed the desired behavior. Thanks for pointing out that this is not obvious, I will add it to the README.

Regarding your edited error messages: It seems you are trying to use a class that is not loaded in the websocket server process yet. It might help to restart the websocket server. In general, keep in mind that changes to code/class autoloading are not reflected in the long running websocket server process until it is restarted.
